### ISSUE TITLE
项目对应的数据库表是什么，运行的时候报错呢

### ISSUE THREAD

**Issue by bizhen-yang** [alibaba/jvm-sandbox-repeater#102]
java.sql.SQLException: Unknown system variable 'query_cache_size'
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964) ~[mysql-connector-java-5.1.42.jar!/:5.1.42]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973) ~[mysql-connector-java-5.1.42.jar!/:5.1.42]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[mysql-connector-java-5.1.42.jar!/:5.1.42]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[mysql-connector-java-5.1.42.jar!/:5.1.42]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[mysql-connector-java-5.1.42.jar!/:5.1.42]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486) ~[mysql-connector-java-5.1.42.jar!/:5.1.42]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2444) ~[mysql-connector-java-5.1.42.jar!/:5.1.42]
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:

**Comment by zhaoyb1990** [comment]
这个跟数据库表无关，应该是数据库驱动和mysql的数据库版本不一致，升级一下驱动即可

**Comment by zhaoyb1990** [comment]
https://github.com/alibaba/jvm-sandbox-repeater/tree/develop20210614  已升级到8.x驱动
