### ISSUE TITLE
使用okhttp3的接口封装的httpUtil工具类方法，录制报错，提示序列化失败

### ISSUE THREAD

**Issue by ElesG** [alibaba/jvm-sandbox-repeater#17]
## repeater代码版本
develop20190829

## 报错时录制的方法
```java
public class HttpUtils {

    /**
     * 等待时间30s
     * 加上日志打印日志
     */
    private static OkHttpClient client = new OkHttpClient.Builder()
            .connectTimeout(30, TimeUnit.SECONDS)
            .readTimeout(30, TimeUnit.SECONDS)
            .addNetworkInterceptor(new HttpLoggingInterceptor(new OkHttpLogger())
                    .setLevel(HttpLoggingInterceptor.Level.BODY))
            .build();


    public static Response post(String url, String body) throws IOException {
        RequestBody requestBody = RequestBody.create(MediaType.parse("application/json;charset=utf-8"), body);
        Request request = new Request.Builder().url(url).post(requestBody).build();
        return client.newCall(request).execute();
    }
}

```

## 报错日志
```
{"data":{"id":36648,"projectType":104043,"name":"自助投[新手流程]","aliasName":"自助投[新手流程]","code":"ZZT1040432019081336648","status":160,"businessType":"103004","remark":null,"descp":null,"availableAmt":9000000.00000,"invtMinAmt":100.00000,"invtMaxAmt":10000000.00000,"invtUnitAmt":100.00000,"rate":12.50000,"maxRate":12.50000,"feeRate":0.00000,"bonusRate":0.00000,"amount":10000000.00000,"totalPeriodCnt":180,"periodType":100,"amortType":180,"frozenDays":30,"frozenDaysType":100,"clientType":7,"exitDurationCnt":null,"perPeriodCnt":null,"perPeriodType":null,"investType":1,"invtStartTime":"2019-08-13 14:31:02","invtEndTime":"2019-08-18 14:31:02","intrStartDate":null,"intrEndDate":null,"assetExchange":"1","matchAssetType":"10","assetNos":"","ruleJson":null,"investCount":null,"couponTypes":[16,17],"supportLockCycleExit":false,"reviveable":false,"supportRevive":false,"supportSetReinvestStrategy":false,"isAutoInvt":0,"productType":100,"feePeriod":null,"isPrivilegeRate":true},"msg":"OK","status":10000000}2019-08-30 20:41:09 DEBUG DefaultEventListener#doBefore.identity={"uri":"java://com.xx.server.utils.HttpUtils/post~(Ljava/lang/String;Ljava/lang/String;)Lokhttp3/Response;"}
2019-08-30 20:41:09 DEBUG DefaultEventListener.onEvent.invokeType=java
2019-08-30 20:41:09 DEBUG DefaultEventListener#doReturn.response=
2019-08-30 20:41:40 ERROR Error occurred serialize
com.alibaba.jvm.sandbox.repeater.plugin.core.serialize.SerializeException: [Error-1001]-hessian-serialize-error
	at com.alibaba.jvm.sandbox.repeater.plugin.core.serialize.HessianSerializer.serialize(HessianSerializer.java:43)
	at com.alibaba.jvm.sandbox.repeater.plugin.core.serialize.AbstractSerializerAdapter.serialize2String(AbstractSerializerAdapter.java:30)
	at com.alibaba.jvm.sandbox.repeater.plugin.core.wrapper.SerializerWrapper.inTimeSerialize(SerializerWrapper.java:98)
	at com.alibaba.jvm.sandbox.repeater.plugin.core.impl.api.DefaultInvocationListener.onInvocation(DefaultInvocationListener.java:41)
	at com.alibaba.jvm.sandbox.repeater.plugin.core.impl.api.DefaultEventListener.doReturn(DefaultEventListener.java:230)
	at com.alibaba.jvm.sandbox.repeater.plugin.core.impl.api.DefaultEventListener.onEvent(DefaultEventListener.java:125)
	at com.alibaba.jvm.sandbox.core.enhance.weaver.EventListenerHandlers.handleEvent(EventListenerHandlers.java:102)
	at com.alibaba.jvm.sandbox.core.enhance.weaver.EventListenerHandlers.handleOnEnd(EventListenerHandlers.java:404)
	at com.alibaba.jvm.sandbox.core.enhance.weaver.EventListenerHandlers.onReturn(EventListenerHandlers.java:579)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.com.alibaba.jvm.sandbox.spy.Spy.spyMethodOnReturn(Spy.java:216)
	at com.xx.server.utils.HttpUtils.post(HttpUtils.java:35)
	at com.xx.server.utils.DingtalkUtils.sendDingtalkMessage(DingtalkUtils.java:28)
	at com.xx.server.delivery.JiraNotificationDelivery.lambda$sendNotification$0(JiraNotificationDelivery.java:47)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.xx.server.delivery.JiraNotificationDelivery.sendNotification(JiraNotificationDelivery.java:47)
	at com.xx.server.impl.AlertServiceImpl.receiveJiraNotification(AlertServiceImpl.java:185)
	at com.xx.server.impl.AlertServiceImpl$$FastClassBySpringCGLIB$$3cd85ab3.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.xx.server.config.WebLogAspect.doAround(WebLogAspect.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.xx.xx.filter.FilterChain$1.filter(FilterChain.java:78)
	at com.xx.xx.filter.FilterChainItem.doFilter(FilterChainItem.java:15)
	at com.xx.xx.server.filter.SimpleServerFilter.filter(SimpleServerFilter.java:27)
	at com.xx.xx.filter.FilterChainItem.doFilter(FilterChainItem.java:15)
	at com.xx.xx.validation.ValidatorFilter.filter(ValidatorFilter.java:65)
	at com.xx.xx.filter.FilterChainItem.doFilter(FilterChainItem.java:15)
	at com.xx.xx.server.filter.SimpleServerFilter.filter(SimpleServerFilter.java:27)
	at com.xx.xx.filter.FilterChainItem.doFilter(FilterChainItem.java:15)
	at com.xx.xx.server.filter.ExceptionFilter.filter(ExceptionFilter.java:32)
	at com.xx.xx.filter.FilterChainItem.doFilter(FilterChainItem.java:15)
	at com.xx.xx.filter.FilterChain.doFilter(FilterChain.java:40)
	at com.xx.xx.filter.GlobalFilterAspect.filter(GlobalFilterAspect.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.xx.server.impl.AlertServiceImpl$$EnhancerBySpringCGLIB$$57882692.receiveJiraNotification(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:112)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.caucho.hessian.io.IOExceptionWrapper: Read timed out

```

**Comment by ElesG** [comment]
想请教一下如果需要对调用外部http接口调用的方法进行mock，那应该如何配置子调用呢？

**Comment by zhaoyb1990** [comment]
对于这种，需要再往上层进行录制，不能直接录制http工具类的返回结果，里面后一些连接不可序列化；

后面会考虑提供更底层的录制方案，但难度比较大。

**Comment by ElesG** [comment]
好的了解了，暂时先通过mock更上层的调用来进行录制吧。感谢:)
