### ISSUE TITLE
dubbo 录制的时候日志报错：no valid classloader found in routing 要怎么处理？

### ISSUE THREAD

**Issue by T-Xbai** [alibaba/jvm-sandbox-repeater#213]
2023-08-09 18:15:51 WARN  no valid classloader found in routing,routing=PluginClassRouting{targetClass='org.apache.dubbo.rpc.model.ApplicationModel', classPattern='^org.apache.dubbo..*', identity='dubbo', matcher=REPEATER, block=false}
2023-08-09 18:15:51 INFO  enable plugin http success
2023-08-09 18:15:52 INFO  add watcher success,type=http,watcherId=1016
2023-08-09 18:15:52 INFO  enable plugin java-entrance success
2023-08-09 18:15:52 ERROR error occurred when initialize module
java.lang.NullPointerException: null
	at com.alibaba.jvm.sandbox.repeater.plugin.core.impl.AbstractInvokePluginAdapter.watchIfNecessary(AbstractInvokePluginAdapter.java:125)
	at com.alibaba.jvm.sandbox.repeater.plugin.core.impl.AbstractInvokePluginAdapter.watch(AbstractInvokePluginAdapter.java:62)
	at com.alibaba.jvm.sandbox.repeater.module.RepeaterModule.initialize(RepeaterModule.java:174)
	at com.alibaba.jvm.sandbox.repeater.module.RepeaterModule.access$500(RepeaterModule.java:64)
	at com.alibaba.jvm.sandbox.repeater.module.RepeaterModule$1.run(RepeaterModule.java:142)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by peterZhang000** [comment]
需要修改这个，dubbo3应该路径不一样了
        // dubbo回放器中对dubbo框架路由
        PluginClassRouting dubboRepeaterRouting = PluginClassRouting.builder()
                .targetClass("org.apache.dubbo.rpc.model.ApplicationModel")
                .classPattern("^org.apache.dubbo..*")
                .identity("dubbo")
                .matcher(Matcher.REPEATER)
                .block(false)
                .build();

**Comment by luoweiyang666** [comment]
我的日志为啥没生成啊，我指定的opt/log目录下，我新建的文件夹，就是那个log文件没新建，为啥没有日志文件生成啊
