### ISSUE TITLE
attach某个进程后的 sandbox 错误日志

### ISSUE THREAD

**Issue by handsometang** [alibaba/jvm-sandbox-repeater#48]
[](url)
![WechatIMG11](https://user-images.githubusercontent.com/41557038/72414625-a2e4e080-37ad-11ea-8057-7b1243de3ea2.jpeg)

**Comment by handsometang** [comment]
at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader.loadClass(RoutingURLClassLoader.java:86)
 at com.alibaba.jvm.sandbox.module.debug.util.InterfaceProxyUtils$2.invoke(InterfaceProxyUtils.java:155)
 at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader.loadClass(RoutingURLClassLoader.java:86)
 at com.alibaba.jvm.sandbox.module.debug.util.InterfaceProxyUtils$2.invoke(InterfaceProxyUtils.java:155)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:78)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:71)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:78)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:71)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:78)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:71)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:78)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:71)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:78)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:71)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:78)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:71)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:78)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:71)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:78)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:71)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:79)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:71)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:79)
 at com.alibaba.jvm.sandbox.repater.plugin.http.wrapper.WrapperRequest.startAsync(WrapperRequest.java:71)



Attach 后再请求（http）需要录制的接口的日志。

**Comment by handsometang** [comment]
[hs_err_pid10999.log](https://github.com/alibaba/jvm-sandbox-repeater/files/4064511/hs_err_pid10999.log)

crash 日志

**Comment by nfw999** [comment]
遇到相同的情况，attach进程后成功录制几条后数据后，宿主进程无响应，然后挂掉

**Comment by nfw999** [comment]
> [hs_err_pid10999.log](https://github.com/alibaba/jvm-sandbox-repeater/files/4064511/hs_err_pid10999.log)
> 
> crash 日志

换个jdk版本试试，或者使用agent方式启动。
我这边同样的问题，换agent方式启动没问题，attach方式更换jdk1.8.0_191也没问题。
具体原因没搞清楚

**Comment by zhaoyb1990** [comment]
你们的Web应用框架能提供吗。 详细的运行环境，从提供的信息无法复现和排查
