### ISSUE TITLE
录制对象存在socket流导致业务请求被阻塞

### ISSUE THREAD

**Issue by angek44** [alibaba/jvm-sandbox-repeater#62]
业务发生阻塞是因为被录制的对象存在socket流导致的，因为在使用hessian序列化时，不支持socket流，会抛错，导致socket关闭，从而出现业务请求被阻塞的现象发生
Caused by: com.caucho.hessian.io.IOExceptionWrapper: Socket closed
 field: java.net.***.socketInputStream
 class: java.net.SocksSocketImpl (object=Socket[addr=/****,port=8623,localport=34642])
  at com.caucho.hessian.io.UnsafeSerializer.writeInstance(UnsafeSerializer.java:224)
  at com.caucho.hessian.io.UnsafeSerializer.writeObject(UnsafeSerializer.java:169)
  at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:465)
  at com.caucho.hessian.io.UnsafeSerializer$ObjectFieldSerializer.serialize(UnsafeSerializer.java:296)
  ... 132 common frames omitted
Caused by: com.caucho.hessian.io.IOExceptionWrapper: Socket closed
 field: java.net.AbstractPlainSocketImpl.socketInputStream
  at com.caucho.hessian.io.UnsafeSerializer$ObjectFieldSerializer.serialize(UnsafeSerializer.java:305)
  at com.caucho.hessian.io.UnsafeSerializer.writeInstance(UnsafeSerializer.java:215)
  ... 135 common frames omitted
Caused by: java.net.SocketException: Socket closed
  at java.net.SocketInputStream.read(SocketInputStream.java:203)
  at java.net.SocketInputStream.read(SocketInputStream.java:141)
  at com.caucho.hessian.io.Hessian2Output.writeByteStream(Hessian2Output.java:1287)
  at com.caucho.hessian.io.InputStreamSerializer.writeObject(InputStreamSerializer.java:70)
  at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:465)
  at com.caucho.hessian.io.UnsafeSerializer$ObjectFieldSerializer.serialize(UnsafeSerializer.java:296)
  ... 136 common frames omitted

**Comment by wuguanyu** [comment]
这个问题真的很麻烦 不大好处理

**Comment by zhaoyb1990** [comment]
避免对象中有类似不可重读的问题，考虑直接关闭Hessian的流序列化功能。

**Comment by masterx0** [comment]
> 避免对象中有类似不可重读的问题，考虑直接关闭Hessian的流序列化功能。

怎么关闭呢请问？我看库里是有把hessian-lite全copy进来使用，但是不知道在哪里可以修改这个配置
