### ISSUE TITLE
在dubbo的consumer端进行录制回放时，使用java来mock dubbo协议回放报错。

### ISSUE THREAD

**Issue by ElesG** [alibaba/jvm-sandbox-repeater#8]
## 环境说明
* 系统：Mac Os 10.14.3 (18D109)
* java版本：
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

## 用来尝试录制回放的项目是dubbo的spring示例项目
https://github.com/apache/dubbo-spring-boot-project/tree/master/dubbo-spring-boot-samples/externalized-configuration-samples

## 复现步骤
1、拉下源码
`git clone https://github.com/apache/dubbo-spring-boot-project.git`
2、使用idea 打开项目
3、到dubbo-spring-boot-samples/externalized-configuration-samples下，先用run provider服务，再run consumer服务
4、修改repeater-console的`/facade/api/config`接口，将返回的配置改为
```
{
    "success": true,
    "data": {
        "pluginsPath": null,
        "exceptionThreshold": 1000,
        "javaEntranceBehaviors": [],
        "pluginIdentities": [
            "http",
            "java-entrance",
            "java-subInvoke",
            "mybatis"
        ],
        "repeatIdentities": [
            "http",
            "java",
            "mybatis"
        ],
        "httpEntrancePatterns": [
            "/say-hello"
        ],
        "sampleRate": 10000,
        "javaSubInvokeBehaviors": [
            {
                "classPattern": "org.apache.dubbo.spring.boot.demo.provider.service.DefaultDemoService",
                "includeSubClasses": false,
                "methodPatterns": [
                    "sayHello"
                ]
            }
        ],
        "useTtl": true,
        "degrade": false
    },
    "message": "operate success"
}
```
5、以attach模式启动repeater，关联consumer服务的进程id
6、请求consumer暴露的`/say-hello`接口，从repeater.log看到录制成功日志，拿到traceId
7、调用repeater-console回放接口进行回放

## 录制、回放过程日志
```
2019-08-05 16:58:46 INFO  broadcast success,traceId=192168015073156499552592010001ed,resp=HttpUtil.Resp(code=200, body={"success":true,"data":"-/-","message":"operate success"}, message=null)
2019-08-05 16:59:00 INFO  subscribe success params={_data=QzA5Y29tLmFsaWJhYmEuanZtLnNhbmRib3gucmVwZWF0ZXIucGx1Z2luLmRvbWFpbi5SZXBlYXRNZXRhmAdhcHBOYW1lB3RyYWNlSWQEbW9jawhyZXBlYXRJZA9tYXRjaFBlcmNlbnRhZ2UKZGF0YXNvdXJjZQxzdHJhdGVneVR5cGUJZXh0ZW5zaW9uYAd1bmtub3duMCAxOTIxNjgwMTUwNzMxNTY0OTk1NTI1OTIwMTAwMDFlZFQwIDE5MjE2ODAxNTA3MzE1NjQ5OTU1NDAyOTQxMDAwMWVkXWROQzBFY29tLmFsaWJhYmEuanZtLnNhbmRib3gucmVwZWF0ZXIucGx1Z2luLnNwaS5Nb2NrU3RyYXRlZ3kkU3RyYXRlZ3lUeXBlkQRuYW1lYQ9QQVJBTUVURVJfTUFUQ0hIWg==}
2019-08-05 16:59:00 INFO  DefaultFlowDispatcher.dispatch中，RecordModel的traceId：192168015073156499552592010001ed，RepeatMeta的traceId：192168015073156499552592010001ed
2019-08-05 16:59:00 INFO  DefaultFlowDispatcher.dispatch中，RepeatMeta的repeatId：192168015073156499552592010001ed
2019-08-05 16:59:00 INFO  recordModel 中 EntranceInvocation 的 type 的名称: "http"
2019-08-05 16:59:00 INFO  传入 select 的 type: http
2019-08-05 16:59:00 INFO  RepeaterBridge 中的所有 cached: {"java":{"type":{}},"dubbo":{"type":{}},"http":{"type":{}}}
2019-08-05 16:59:00 INFO  cached 中具有的 type: java
2019-08-05 16:59:00 INFO  cached 中的 type java 和传入的 type com.alibaba.jvm.sandbox.repeater.plugin.domain.InvokeType$1@763784d2 作 equals 的结果: false
2019-08-05 16:59:00 INFO  cached 中具有的 type: dubbo
2019-08-05 16:59:00 INFO  cached 中的 type dubbo 和传入的 type com.alibaba.jvm.sandbox.repeater.plugin.domain.InvokeType$1@763784d2 作 equals 的结果: false
2019-08-05 16:59:00 INFO  cached 中具有的 type: http
2019-08-05 16:59:00 INFO  cached 中的 type http 和传入的 type com.alibaba.jvm.sandbox.repeater.plugin.domain.InvokeType$1@763784d2 作 equals 的结果: true
2019-08-05 16:59:00 INFO  AbstractRepeater.repeat中的traceId：192168015073156499554079210002ed
2019-08-05 16:59:00 INFO  AbstractRepeater.repeat中的repeatId：192168015073156499554029410001ed
2019-08-05 16:59:00 INFO  broadcastRepeat中的traceId：192168015073156499554079210002ed
2019-08-05 16:59:00 INFO  broadcastRepeat中的repeatId：192168015073156499554029410001ed
2019-08-05 16:59:00 INFO  broadcast success,traceId=192168015073156499554079210002ed,resp=HttpUtil.Resp(code=200, body={"success":true,"data":"-/-","message":"operate success"}, message=null)

```

## consumer报错日志
```
2019-08-05 16:38:24.038 ERROR 55981 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.reflect.UndeclaredThrowableException] with root cause

java.lang.RuntimeException: DubboProcessor#assembleRequest only receive #onResponse behavior
	at com.alibaba.jvm.sandbox.repeater.plugin.dubbo.DubboProcessor.assembleRequest(DubboProcessor.java:59) ~[na:na]
	at com.alibaba.jvm.sandbox.repeater.plugin.core.impl.AbstractInvocationProcessor.doMock(AbstractInvocationProcessor.java:70) ~[na:na]
	at com.alibaba.jvm.sandbox.repeater.plugin.core.impl.api.DefaultEventListener.doBefore(DefaultEventListener.java:171) ~[na:na]
	at com.alibaba.jvm.sandbox.repeater.plugin.core.impl.api.DefaultEventListener.onEvent(DefaultEventListener.java:124) ~[na:na]
	at com.alibaba.jvm.sandbox.core.enhance.weaver.EventListenerHandlers.handleEvent(EventListenerHandlers.java:102) ~[na:na]
	at com.alibaba.jvm.sandbox.core.enhance.weaver.EventListenerHandlers.handleOnBefore(EventListenerHandlers.java:342) ~[na:na]
	at com.alibaba.jvm.sandbox.core.enhance.weaver.EventListenerHandlers.onBefore(EventListenerHandlers.java:565) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at java.com.alibaba.jvm.sandbox.spy.Spy.spyMethodOnBefore(Spy.java:193) ~[na:na]
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:57) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.common.bytecode.proxy0.sayHello(proxy0.java) ~[dubbo-2.7.1.jar:2.7.1]
	at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor$ReferenceBeanInvocationHandler.invoke(ReferenceAnnotationBeanPostProcessor.java:165) ~[dubbo-2.7.1.jar:2.7.1]
	at com.sun.proxy.$Proxy80.sayHello(Unknown Source) ~[na:na]
	at org.apache.dubbo.spring.boot.demo.consumer.bootstrap.DubboExternalizedConfigurationConsumerBootstrap.sayHello(DubboExternalizedConfigurationConsumerBootstrap.java:49) ~[classes/:na]
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90) ~[spring-boot-actuator-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117) ~[spring-boot-actuator-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106) ~[spring-boot-actuator-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834) [tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415) [tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.16.jar:9.0.16]
	at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:51) [sandbox_module_jar_6023817277835998588.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.16.jar:9.0.16]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
```

**Comment by zhaoyb1990** [comment]
确认是bug；回放的时候assembleRequest需要通过`invoke`来组装；

**Comment by ElesG** [comment]
> 确认是bug；回放的时候assembleRequest需要通过`invoke`来组装；

请问这个问题可以通过配置来绕过吗？或者说可以通过什么样的配置来实现这样的场景：当一个http接口，他其中的某个步骤调用了dubbo的协议，我需要mock掉这个dubbo调用。

**Comment by zhaoyb1990** [comment]
> 请问这个问题可以通过配置来绕过吗？或者说可以通过什么样的配置来实现这样的场景：当一个http接口，他其中的某个步骤调用了dubbo的协议，我需要mock掉这个dubbo调用。

无法绕过，会尽快提交修复

**Comment by ElesG** [comment]
> > 请问这个问题可以通过配置来绕过吗？或者说可以通过什么样的配置来实现这样的场景：当一个http接口，他其中的某个步骤调用了dubbo的协议，我需要mock掉这个dubbo调用。
> 
> 无法绕过，会尽快提交修复

请问可以讲解一下是什么问题引起的bug吗？看能不能我协助修复。

> 回放的时候assembleRequest需要通过invoke来组装；
我对这句话的理解是，assembleRequest需要通过invoke来组装，所以assembleRequest判断的条件应该是非INVOKE的请求不接受处理？
然后我对代码做了如下的调整：
```
  @Override
    public Identity assembleIdentity(BeforeEvent event) {
        // interfaceName 兼容了invoke的场景
        Object invocation = INVOKE.equals(event.javaMethodName) ? event.argumentArray[1] : event.argumentArray[2];
        try {
            // methodName
            String methodName = (String) MethodUtils.invokeMethod(invocation, "getMethodName");
            Class<?>[] parameterTypes = (Class<?>[]) MethodUtils.invokeMethod(invocation, "getParameterTypes");
            String interfaceName = (String) MethodUtils.invokeMethod(invocation, "getAttachment", "interface");
           // 看了dubbo协议源码发现ConsumerContextFilter没有setAttachment，所以interfaceName为空，在这里做了兼容
            if(interfaceName == null){
                interfaceName = "invoke-unknown";
            }
            return new Identity(InvokeType.DUBBO.name(), interfaceName, getMethodDesc(methodName, parameterTypes), null);
        } catch (Exception e) {
            // ignore
            LogUtil.error("error occurred when assemble dubbo request", e);
        }
        return new Identity(InvokeType.DUBBO.name(), "unknown", "unknown", null);
    }

    @Override
    public Object[] assembleRequest(BeforeEvent event) {
        // invoke Result invoke(Invoker<?> invoker, Invocation invocation){}
        if (!INVOKE.equals(event.javaMethodName)) {
            throw new RuntimeException("DubboProcessor#assembleRequest only receive #invoke behavior");
        }
        log.info("DubboProcessor#assembleRequest event.argumentArray.length:{}", event.argumentArray.length);
        try {
            return (Object[]) MethodUtils.invokeMethod(event.argumentArray[1], "getArguments");
        } catch (Exception e) {
            // ignore
            LogUtil.error("error occurred when assemble dubbo request", e);
        }
        return null;
    }
```


修改成上面的源码之后发现代码执行到回放的时候报错了，报错的类是`com.alibaba.jvm.sandbox.repeater.plugin.core.impl.spi.ParameterMatchMockStrategy`
报错原因：

```
@MetaInfServices(MockStrategy.class)
public class ParameterMatchMockStrategy extends AbstractMockStrategy {

    @Override
    protected SelectResult select(MockRequest request) {
        Stopwatch stopwatch = Stopwatch.createStarted();
//由于这里获取到的subInvocations是null，导致后面遍历报出NPE
        List<Invocation> subInvocations = request.getRecordModel().getSubInvocations();
        List<Invocation> target = Lists.newArrayList();

        // 先根据URI进行过滤
        for (Invocation invocation : subInvocations){
            if (invocation.getIdentity().getUri().equals(request.getIdentity().getUri())) {
                target.add(invocation);
            }
        }
```

即使在遍历前做了空指针判断绕过，但在最后回放仍然会由于` no matching invocation found`导致回放失败。

### 解题过程的疑问
是录制的配置有问题么？还是我的解题思路错了呢？
对dubbo框架不大了解，从文档+源码中接口的注释来看，大概明白invoke方法是调用远程函数的方法，那么onResponse方法又是做什么处理的呢？为什么provider只需要录制onResponse而Consumer需要录制invoke和onResponse呢？

**Comment by ElesG** [comment]
在这次用到的dubbo示例项目中对`ContextFilter`和`ConsumerContextFilter`进行了断点，发现一次基于dubbo协议的调用一定会经过这两个Filter的onResponse方法。并且在onResponse方法中才有完整的attachments信息。


于是尝试另外的思路进行：仅对onResponse进行埋点。
步骤如下
1、先将之前对`com.alibaba.jvm.sandbox.repeater.plugin.dubbo.DubboProcessor`的调整恢复到未进行修改的版本。并在`assembleRequest `方法中添加了开始执行的日志打印。
```
    @Override
    public Object[] assembleRequest(BeforeEvent event) {
        // onResponse(Result appResponse, Invoker<?> invoker, Invocation invocation) {}
        log.info("start DubboProcessor#assembleRequest {}", event.javaMethodName);
        if (!ON_RESPONSE.equals(event.javaMethodName)) {
            throw new RuntimeException("DubboProcessor#assembleRequest only receive #onResponse behavior");
        }
```
2、将`com.alibaba.jvm.sandbox.repeater.plugin.dubbo.DubboConsumerPlugin`中的invoke埋点去掉。
```
    @Override
    protected List<EnhanceModel> getEnhanceModels() {
        EnhanceModel onResponse = EnhanceModel.builder().classPattern("org.apache.dubbo.rpc.filter.ConsumerContextFilter$ConsumerContextListener")
                .methodPatterns(EnhanceModel.MethodPattern.transform("onResponse"))
                .watchTypes(Event.Type.BEFORE,Event.Type.RETURN, Event.Type.THROWS)
                .build();
//        EnhanceModel invoke = EnhanceModel.builder().classPattern("org.apache.dubbo.rpc.filter.ConsumerContextFilter")
//                .methodPatterns(EnhanceModel.MethodPattern.transform("invoke"))
//                .watchTypes(Event.Type.BEFORE,Event.Type.RETURN, Event.Type.THROWS)
//                .build();
        log.info("DubboConsumerPlugin onResponse:{}", JSONObject.toJSONString(onResponse, SerializerFeature.IgnoreNonFieldGetter));
//        log.info("DubboConsumerPlugin invoke:{}", JSONObject.toJSONString(invoke, SerializerFeature.IgnoreNonFieldGetter));
        return Lists.newArrayList(onResponse);
    }
```
3、执行repeater中的`bin/install-local.sh`重新打包，并重载了repeater插件和配置。
4、按照问题描述中的步骤重新进行dubbo协议的录制回放。

此时发现回放可以成功，但是却没有mock掉对provider的调用（回放时provider有被调用的日志打印出来）。从repeater.log的日志上看，也没看出来有调用到`assembleRequest`的日志打印出来。
```
2019-08-06 22:46:53 INFO  broadcast success,traceId=192168015073156510281350510003ed,resp=HttpUtil.Resp(code=200, body={"success":true,"data":"-/-","message":"operate success"}, message=null)

2019-08-06 22:47:06 INFO  broadcast success,traceId=192168015073156510282683010004ed,resp=HttpUtil.Resp(code=200, body={"success":true,"data":"-/-","message":"operate success"}, message=null)

```

**Comment by zhaoyb1990** [comment]
使用最新master分支利用dubbo consumer插件进行mock可以解决
